import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:io';
import '../util.dart' show generatePdfBytes;
import '../utils/pdf_utils.dart';
import '../utils/word_utils.dart';
import '../utils/xlsx_utils.dart';
import '../utils/pptx_utils.dart';
import '../utils/text_utils.dart';
import '../utils/image_utils.dart';
import 'dart:ui' as ui;
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:markdown/markdown.dart' as md;

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final TextEditingController _contentController = TextEditingController();
  final FocusNode _contentFocusNode = FocusNode();
  int _selectedThemeIndex = 0;
  ui.Image? _previewImage;
  bool _isPreviewing = false;
  double _fontSize = 32.0;
  String _selectedFont = 'Roboto';

  final List<String> _availableFonts = [
    'Roboto',
    'Arial',
    'Times New Roman',
    'Courier New',
    'Georgia',
    'Verdana',
    'Helvetica',
    'Tahoma',
    'Trebuchet MS',
    'Impact',
  ];

  @override
  void initState() {
    super.initState();
    _contentFocusNode.addListener(() {
      if (!_contentFocusNode.hasFocus) {
        FocusScope.of(context).unfocus();
      }
    });
  }

  @override
  void dispose() {
    _contentController.dispose();
    _contentFocusNode.dispose();
    super.dispose();
  }

  Future<void> _generatePDF() async {
    if (_contentController.text.isEmpty) {
      Fluttertoast.showToast(
        msg: 'Please enter content',
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
      );
      return;
    }

    try {
      final String markdownContent = _contentController.text;

      final pdfBytes = await generatePdfBytes(markdownContent);

      // 获取应用文档目录
      final directory = await getApplicationDocumentsDirectory();
      final now = DateTime.now();
      final fileName =
          '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}_${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}.pdf';
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(pdfBytes);

      // 保存到历史记录
      await PDFUtils.savePDFAndAddToHistory(
        pdfFile: file,
        title: markdownContent.substring(0, min(markdownContent.length, 20)),
      );

      if (mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'PDF document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate PDF: $e');
      if (mounted) {
        Fluttertoast.showToast(
          msg: 'Failed to generate PDF: $e',
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
        );
      }
    }
  }

  Future<void> _generateWord() async {
    if (_contentController.text.isEmpty) {
      Fluttertoast.showToast(
        msg: 'Please enter content',
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
      );
      return;
    }

    try {
      final file =
          await WordUtils.generateWordFromMarkdown(_contentController.text);

      if (mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'Word document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate Word document: $e');
      if (mounted) {
        Fluttertoast.showToast(
          msg: 'Failed to generate Word document: $e',
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
        );
      }
    }
  }

  Future<void> _generateXlsx() async {
    if (_contentController.text.isEmpty) {
      Fluttertoast.showToast(
        msg: 'Please enter content',
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
      );
      return;
    }

    try {
      final file =
          await XlsxUtils.generateXlsxFromMarkdown(_contentController.text);

      if (mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'Excel document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate Excel document: $e');
      if (mounted) {
        Fluttertoast.showToast(
          msg: 'Failed to generate Excel document: $e',
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
        );
      }
    }
  }

  Future<void> _generatePPTX() async {
    if (_contentController.text.isEmpty) {
      Fluttertoast.showToast(
        msg: 'Please enter content',
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
      );
      return;
    }

    try {
      final file =
          await PPTXUtils.generatePPTXFromMarkdown(_contentController.text);

      if (mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'PowerPoint document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate PowerPoint document: $e');
      if (mounted) {
        Fluttertoast.showToast(
          msg: 'Failed to generate PowerPoint document: $e',
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
        );
      }
    }
  }

  Future<void> _generateText() async {
    if (_contentController.text.isEmpty) {
      Fluttertoast.showToast(
        msg: 'Please enter content',
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
      );
      return;
    }

    try {
      final file =
          await TextUtils.generateTextFromContent(_contentController.text);

      if (mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'Text document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate Text document: $e');
      if (mounted) {
        Fluttertoast.showToast(
          msg: 'Failed to generate Text document: $e',
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
        );
      }
    }
  }

  Future<void> _generatePreviewImage({int? themeIndex}) async {
    setState(() {
      _isPreviewing = true;
    });
    final img = await ImageUtils.previewImageFromText(
      _contentController.text,
      kImageThemes[themeIndex ?? _selectedThemeIndex],
      fontSize: _fontSize,
      fontFamily: _selectedFont,
    );
    setState(() {
      _previewImage = img;
      if (themeIndex != null) _selectedThemeIndex = themeIndex;
      _isPreviewing = false;
    });
  }

  void _showImagePreviewDrawer() async {
    if (_contentController.text.isEmpty) {
      Fluttertoast.showToast(
        msg: 'Please enter content',
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.CENTER,
      );
      return;
    }
    await _generatePreviewImage();
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setModalState) {
            return Container(
              height: MediaQuery.of(context).size.height * 2 / 3,
              padding: const EdgeInsets.all(16.0),
              decoration: BoxDecoration(
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.05),
                    offset: const Offset(0, -2),
                    blurRadius: 4,
                  ),
                ],
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text('Image Preview',
                      style:
                          TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 16),
                  if (_isPreviewing)
                    const Expanded(
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    )
                  else if (_previewImage != null)
                    Expanded(
                      child: SingleChildScrollView(
                        child: RawImage(
                          image: _previewImage,
                          fit: BoxFit.contain,
                        ),
                      ),
                    ),
                  const SizedBox(height: 16),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      _buildOptionButton(
                        icon: Icons.palette_outlined,
                        label: 'Theme',
                        onTap: () {
                          showModalBottomSheet(
                            barrierColor: Colors.transparent,
                            context: context,
                            builder: (context) {
                              return Container(
                                padding: const EdgeInsets.all(16),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    const Text('Select Theme',
                                        style: TextStyle(
                                            fontSize: 18,
                                            fontWeight: FontWeight.bold)),
                                    const SizedBox(height: 16),
                                    SizedBox(
                                      height: 200,
                                      child: GridView.builder(
                                        gridDelegate:
                                            const SliverGridDelegateWithFixedCrossAxisCount(
                                          crossAxisCount: 2,
                                          childAspectRatio: 2.5,
                                          crossAxisSpacing: 10,
                                          mainAxisSpacing: 10,
                                        ),
                                        itemCount: kImageThemes.length,
                                        itemBuilder: (context, index) {
                                          final theme = kImageThemes[index];
                                          return GestureDetector(
                                            onTap: () async {
                                              setModalState(() {
                                                _isPreviewing = true;
                                              });
                                              final img = await ImageUtils
                                                  .previewImageFromText(
                                                _contentController.text,
                                                theme,
                                                fontSize: _fontSize,
                                              );
                                              setModalState(() {
                                                _previewImage = img;
                                                _selectedThemeIndex = index;
                                                _isPreviewing = false;
                                              });
                                            },
                                            child: Container(
                                              padding: const EdgeInsets.all(8),
                                              decoration: BoxDecoration(
                                                color:
                                                    theme.backgroundColors[0],
                                                border: Border.all(
                                                  color: Colors.transparent,
                                                  width: 2,
                                                ),
                                                borderRadius:
                                                    BorderRadius.circular(8),
                                              ),
                                              child: Center(
                                                child: Text(
                                                  theme.name,
                                                  style: TextStyle(
                                                      color: theme.textColor),
                                                ),
                                              ),
                                            ),
                                          );
                                        },
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            },
                          );
                        },
                      ),
                      _buildOptionButton(
                        icon: Icons.format_size,
                        label: 'Font Size',
                        onTap: () {
                          _showFontSizeDrawer(setModalState);
                        },
                      ),
                      //Font
                      _buildOptionButton(
                        icon: Icons.font_download,
                        label: 'Font',
                        onTap: () {
                          _showFontDrawer(setModalState);
                        },
                      ),
                      _buildOptionButton(
                        icon: Icons.save_alt,
                        label: 'Save',
                        onTap: () async {
                          try {
                            // 检查权限
                            PermissionStatus status = PermissionStatus.denied;
                            if (Platform.isAndroid) {
                              if (await Permission
                                  .manageExternalStorage.isGranted) {
                                status = PermissionStatus.granted;
                              } else {
                                status = await Permission.manageExternalStorage
                                    .request();
                                if (status.isGranted) {
                                  // 授权成功
                                } else if (status.isPermanentlyDenied) {
                                  // 引导用户去设置
                                  await openAppSettings();
                                } else {
                                  // 拒绝
                                }
                              }
                            } else if (Platform.isIOS) {
                              status = await Permission.photos.request();
                            }

                            if (!status.isGranted) {
                              if (status.isPermanentlyDenied) {
                                // 显示设置对话框
                                final openSettings = await showDialog<bool>(
                                  context: context,
                                  builder: (BuildContext context) {
                                    return AlertDialog(
                                      title: const Text('Permission Denied'),
                                      content: const Text(
                                          'Please enable storage permission in settings'),
                                      actions: <Widget>[
                                        TextButton(
                                          child: const Text('Cancel'),
                                          onPressed: () {
                                            Navigator.of(context).pop(false);
                                          },
                                        ),
                                        TextButton(
                                          child: const Text('Settings'),
                                          onPressed: () {
                                            Navigator.of(context).pop(true);
                                          },
                                        ),
                                      ],
                                    );
                                  },
                                );

                                if (openSettings == true) {
                                  await openAppSettings();
                                }
                              } else {
                                Fluttertoast.showToast(
                                  msg:
                                      'Storage permission is required to save image',
                                  toastLength: Toast.LENGTH_SHORT,
                                  gravity: ToastGravity.CENTER,
                                );
                              }
                              return;
                            }

                            setModalState(() {
                              _isPreviewing = true;
                            });

                            final file = await ImageUtils.generateImageFromText(
                              _contentController.text,
                              kImageThemes[_selectedThemeIndex],
                            );

                            final bytes = await file.readAsBytes();
                            final result = await ImageGallerySaver.saveImage(
                                bytes,
                                quality: 100,
                                name:
                                    "AI_Transfer_${DateTime.now().millisecondsSinceEpoch}");

                            setModalState(() {
                              _isPreviewing = false;
                            });

                            if (result['isSuccess']) {
                              Fluttertoast.showToast(
                                msg: 'Image saved to gallery',
                                toastLength: Toast.LENGTH_SHORT,
                                gravity: ToastGravity.CENTER,
                              );
                            } else {
                              Fluttertoast.showToast(
                                msg: 'Save failed',
                                toastLength: Toast.LENGTH_SHORT,
                                gravity: ToastGravity.CENTER,
                              );
                            }
                          } catch (e) {
                            print('Save image failed: $e');
                            setModalState(() {
                              _isPreviewing = false;
                            });
                            Fluttertoast.showToast(
                              msg: 'Save failed: $e',
                              toastLength: Toast.LENGTH_SHORT,
                              gravity: ToastGravity.CENTER,
                            );
                          }
                        },
                      ),
                    ],
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  void _showFontSizeDrawer(StateSetter setModalState) {
    showModalBottomSheet(
      context: context,
      barrierColor: Colors.transparent,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setState) {
            return Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.05),
                    offset: const Offset(0, -2),
                    blurRadius: 4,
                  ),
                ],
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text(
                    'Adjust Font Size',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 16),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      IconButton(
                        icon: const Icon(Icons.remove),
                        onPressed: () async {
                          if (_fontSize > 16) {
                            setModalState(() {
                              _isPreviewing = true;
                            });
                            final img = await ImageUtils.previewImageFromText(
                              _contentController.text,
                              kImageThemes[_selectedThemeIndex],
                              fontSize: _fontSize - 2,
                            );
                            setModalState(() {
                              _previewImage = img;
                              _isPreviewing = false;
                            });
                            setState(() {
                              _fontSize -= 2;
                            });
                          }
                        },
                      ),
                      Text(
                        '${_fontSize.toInt()}',
                        style: const TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.add),
                        onPressed: () async {
                          if (_fontSize < 40) {
                            setModalState(() {
                              _isPreviewing = true;
                            });
                            final img = await ImageUtils.previewImageFromText(
                              _contentController.text,
                              kImageThemes[_selectedThemeIndex],
                              fontSize: _fontSize + 2,
                            );
                            setModalState(() {
                              _previewImage = img;
                              _isPreviewing = false;
                            });
                            setState(() {
                              _fontSize += 2;
                            });
                          }
                        },
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  Slider(
                    value: _fontSize,
                    min: 16,
                    max: 48,
                    divisions: 16,
                    label: _fontSize.toInt().toString(),
                    onChanged: (value) async {
                      setModalState(() {
                        _isPreviewing = true;
                      });
                      final img = await ImageUtils.previewImageFromText(
                        _contentController.text,
                        kImageThemes[_selectedThemeIndex],
                        fontSize: value,
                      );
                      setModalState(() {
                        _previewImage = img;
                        _isPreviewing = false;
                      });
                      setState(() {
                        _fontSize = value;
                      });
                    },
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  void _showFontDrawer(StateSetter setModalState) {
    showModalBottomSheet(
      barrierColor: Colors.transparent,
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setState) {
            return Container(
              height: MediaQuery.of(context).size.height * 0.4,
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.05),
                    offset: const Offset(0, -2),
                    blurRadius: 4,
                  ),
                ],
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text(
                    'Select Font',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 16),
                  Expanded(
                    child: ListView.builder(
                      itemCount: _availableFonts.length,
                      itemBuilder: (context, index) {
                        final font = _availableFonts[index];
                        return ListTile(
                          title: Text(
                            'Hello, world!',
                            style: TextStyle(
                              fontFamily: font,
                              fontSize: 16,
                            ),
                          ),
                          subtitle: Text(font),
                          selected: font == _selectedFont,
                          onTap: () async {
                            setModalState(() {
                              _isPreviewing = true;
                            });
                            final img = await ImageUtils.previewImageFromText(
                              _contentController.text,
                              kImageThemes[_selectedThemeIndex],
                              fontSize: _fontSize,
                              fontFamily: font,
                            );
                            setModalState(() {
                              _previewImage = img;
                              _isPreviewing = false;
                            });
                            setState(() {
                              _selectedFont = font;
                            });
                          },
                        );
                      },
                    ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  Widget _buildOptionButton({
    required IconData icon,
    required String label,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 48,
            height: 48,
            decoration: BoxDecoration(
              color: Colors.blue.withOpacity(0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(icon, color: Colors.blue[700]),
          ),
          const SizedBox(height: 4),
          Text(label, style: TextStyle(fontSize: 12, color: Colors.grey[700])),
        ],
      ),
    );
  }

  Widget _buildPasteButton(TextEditingController controller) {
    return Row(
      children: [
        GestureDetector(
          onTap: () {
            controller.clear();
            setState(() {});
          },
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: Colors.red.withOpacity(0.1),
              borderRadius: BorderRadius.circular(6),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.clear, size: 16, color: Colors.red[700]),
                const SizedBox(width: 4),
                Text('Clear', style: TextStyle(color: Colors.red[700])),
              ],
            ),
          ),
        ),
        const SizedBox(width: 8),
        GestureDetector(
          onTap: () async {
            ClipboardData? data = await Clipboard.getData('text/plain');
            if (data != null && data.text != null) {
              controller.text = data.text!;
              setState(() {});
            }
          },
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: Colors.blue.withOpacity(0.1),
              borderRadius: BorderRadius.circular(6),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.copy, size: 16, color: Colors.blue[700]),
                const SizedBox(width: 4),
                Text('Paste', style: TextStyle(color: Colors.blue[700])),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildInputSection(String title, TextEditingController controller) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(title,
                  style: const TextStyle(
                      fontSize: 16, fontWeight: FontWeight.w500)),
              _buildPasteButton(controller),
            ],
          ),
        ),
        const SizedBox(height: 8),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: TextField(
            controller: controller,
            focusNode: _contentFocusNode,
            maxLines: 10,
            decoration: InputDecoration(
              hintText: 'Enter main content',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
              contentPadding: const EdgeInsets.all(12),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildFormatButton(IconData icon, String label, VoidCallback onTap) {
    return GestureDetector(
        onTap: onTap,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 48,
              height: 48,
              decoration: BoxDecoration(
                color: Colors.blue.withOpacity(0.1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Icon(icon, color: Colors.blue[700]),
            ),
            const SizedBox(height: 4),
            Text(label,
                style: TextStyle(fontSize: 12, color: Colors.grey[700])),
          ],
        ));
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
      },
      child: Scaffold(
        resizeToAvoidBottomInset: true,
        appBar: AppBar(
          title: const Text('AI Transfer'),
          centerTitle: true,
        ),
        body: LayoutBuilder(
          builder: (context, constraints) {
            return SingleChildScrollView(
              padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom,
              ),
              child: ConstrainedBox(
                constraints: BoxConstraints(
                  minHeight: constraints.maxHeight,
                ),
                child: IntrinsicHeight(
                  child: Column(
                    children: [
                      Expanded(
                        child: _buildInputSection(
                            'Main Content', _contentController),
                      ),
                      Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(0.05),
                              blurRadius: 10,
                              offset: const Offset(0, -2),
                            ),
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(left: 8.0, bottom: 12.0),
                              child: Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    'Format',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                  Text(
                                    'Click icon to convert',
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: Colors.grey,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceAround,
                              children: [
                                _buildFormatButton(Icons.description_outlined,
                                    'Word', _generateWord),
                                _buildFormatButton(
                                    Icons.picture_as_pdf_outlined,
                                    'PDF',
                                    _generatePDF),
                                _buildFormatButton(Icons.slideshow_outlined,
                                    'Slides', _generatePPTX),
                                _buildFormatButton(Icons.table_chart_outlined,
                                    'Sheet', _generateXlsx),
                                _buildFormatButton(Icons.image_outlined,
                                    'Image', _showImagePreviewDrawer),
                                _buildFormatButton(Icons.text_fields_outlined,
                                    'Text', _generateText),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }

  static List<TextSpan> _parseMarkdownToTextSpans(
      String markdownText, Color textColor, double fontSize) {
    final document = md.Document(
      extensionSet: md.ExtensionSet.gitHubWeb,
      encodeHtml: false,
    );

    // 预处理文本，确保换行符统一
    final processedText =
        markdownText.replaceAll('\r\n', '\n').replaceAll('\r', '\n');

    // 预处理任务列表
    final processedLines = processedText.split('\n').map((line) {
      if (line.trim().startsWith('- [ ]')) {
        return line.replaceFirst('- [ ]', '* [ ]');
      } else if (line.trim().startsWith('- [x]') ||
          line.trim().startsWith('- [X]')) {
        return line.replaceFirst(RegExp(r'- \[[xX]\]'), '* [x]');
      }
      return line;
    }).join('\n');

    final nodes = document.parseLines(processedLines.split('\n'));
    final spans = <TextSpan>[];

    void processNode(md.Node node) {
      if (node is md.Text) {
        spans.add(TextSpan(
          text: node.text,
          style: TextStyle(
            color: textColor,
            fontSize: fontSize,
          ),
        ));
      } else if (node is md.Element) {
        switch (node.tag) {
          case 'strong':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
                fontWeight: FontWeight.bold,
              ),
            ));
            break;
          case 'em':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
                fontStyle: FontStyle.italic,
              ),
            ));
            break;
          case 'h1':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize * 1.25,
                fontWeight: FontWeight.bold,
              ),
            ));
            spans.add(const TextSpan(text: '\n\n'));
            break;
          case 'h2':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize * 1.15,
                fontWeight: FontWeight.bold,
              ),
            ));
            spans.add(const TextSpan(text: '\n\n'));
            break;
          case 'h3':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize * 1.1,
                fontWeight: FontWeight.bold,
              ),
            ));
            spans.add(const TextSpan(text: '\n\n'));
            break;
          case 'p':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'ul':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'ol':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'li':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'blockquote':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'code':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'pre':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'a':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'img':
            spans.add(TextSpan(
              text: node.textContent,
              style: TextStyle(
                color: textColor,
                fontSize: fontSize,
              ),
            ));
            break;
          case 'br':
            spans.add(TextSpan(text: '\n'));
            break;
          default:
            if (node.children != null && node.children!.isNotEmpty) {
              processNode(node.children![0]);
            }
        }
      }
    }

    for (var node in nodes) {
      processNode(node);
    }

    return spans;
  }
}
