import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:flutter/material.dart';
import 'package:markdown/markdown.dart' as md;
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'dart:math';
import 'dart:ui' as ui;

import '../models/history_item.dart';
import '../services/history_service.dart';
import '../util.dart' show generatePdfBytes;
import 'pdf_utils.dart';
import 'word_utils.dart';
import 'xlsx_utils.dart';
import 'pptx_utils.dart';
import 'text_utils.dart';
import 'image_utils.dart';
import 'history_utils.dart';

class FileGenerator {
  /// 生成并分享PDF文件
  static Future<void> generateAndSharePDF(String content, BuildContext context) async {
    if (content.isEmpty) {
      _showToast('请输入内容');
      return;
    }

    try {
      final pdfBytes = await generatePdfBytes(content);
      final directory = await getApplicationDocumentsDirectory();
      final now = DateTime.now();
      final fileName = '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}_${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}.pdf';
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(pdfBytes);

      await HistoryUtils.addFileToHistory(
        file: file,
        title: content.substring(0, min(content.length, 20)),
        rawData: content,
        type: 'PDF',
      );

      if (context.mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'PDF document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate PDF: $e');
      _showToast('生成PDF失败: $e');
    }
  }

  /// 生成并分享Word文件
  static Future<void> generateAndShareWord(String content, BuildContext context) async {
    if (content.isEmpty) {
      _showToast('请输入内容');
      return;
    }

    try {
      final file = await WordUtils.generateWordFromMarkdown(content);
      await HistoryUtils.addFileToHistory(
        file: file,
        title: content.substring(0, min(content.length, 20)),
        rawData: content,
        type: 'Word',
      );

      if (context.mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'Word document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate Word document: $e');
      _showToast('生成Word文件失败: $e');
    }
  }

  /// 生成并分享Excel文件
  static Future<void> generateAndShareExcel(String content, BuildContext context) async {
    if (content.isEmpty) {
      _showToast('请输入内容');
      return;
    }

    try {
      final file = await XlsxUtils.generateXlsxFromMarkdown(content);
      await HistoryUtils.addFileToHistory(
        file: file,
        title: content.substring(0, min(content.length, 20)),
        rawData: content,
        type: 'Sheet',
      );

      if (context.mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'Excel document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate Excel document: $e');
      _showToast('生成Excel文件失败: $e');
    }
  }

  /// 生成并分享PowerPoint文件
  static Future<void> generateAndSharePowerPoint(String content, BuildContext context) async {
    if (content.isEmpty) {
      _showToast('请输入内容');
      return;
    }

    try {
      final file = await PPTXUtils.generatePPTXFromMarkdown(content);
      await HistoryUtils.addFileToHistory(
        file: file,
        title: content.substring(0, min(content.length, 20)),
        rawData: content,
        type: 'Slides',
      );

      if (context.mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'PowerPoint document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate PowerPoint document: $e');
      _showToast('生成PowerPoint文件失败: $e');
    }
  }

  /// 生成并分享文本文件
  static Future<void> generateAndShareText(String content, BuildContext context) async {
    if (content.isEmpty) {
      _showToast('请输入内容');
      return;
    }

    try {
      final file = await TextUtils.generateTextFromContent(content);
      await HistoryUtils.addFileToHistory(
        file: file,
        title: content.substring(0, min(content.length, 20)),
        rawData: content,
        type: 'Text',
      );

      if (context.mounted) {
        await Share.shareXFiles(
          [XFile(file.path)],
          text: 'Text document generated by AI Transfer',
        );
      }
    } catch (e) {
      print('Failed to generate Text document: $e');
      _showToast('生成文本文件失败: $e');
    }
  }

  /// 生成并保存图片
  static Future<void> generateAndSaveImage(
    String content,
    int themeIndex,
    double fontSize,
    String fontFamily,
    BuildContext context,
    Function(bool) onLoadingChanged,
  ) async {
    if (content.isEmpty) {
      _showToast('请输入内容');
      return;
    }

    try {
      onLoadingChanged(true);
      final image = await ImageUtils.previewImageFromText(
        content,
        kImageThemes[themeIndex],
        fontSize: fontSize,
        fontFamily: fontFamily,
      );

      final bytes = await image.toByteData(format: ui.ImageByteFormat.png);
      final pngBytes = bytes!.buffer.asUint8List();
      
      final result = await ImageGallerySaver.saveImage(
        pngBytes,
        quality: 100,
        name: "AI_Transfer_${DateTime.now().millisecondsSinceEpoch}",
      );

      if (result['isSuccess']) {
        _showToast('图片已保存到相册');
        final directory = await getApplicationDocumentsDirectory();
        final fileName = "AI_Transfer_${DateTime.now().millisecondsSinceEpoch}.png";
        final file = File('${directory.path}/$fileName');
        await file.writeAsBytes(pngBytes);
        
        await HistoryUtils.addFileToHistory(
          file: file,
          title: 'image_${DateTime.now().millisecondsSinceEpoch}',
          rawData: content,
          type: 'Image',
        );
      } else {
        _showToast('保存失败');
      }
    } catch (e) {
      print('Failed to generate image: $e');
      _showToast('生成图片失败: $e');
    } finally {
      onLoadingChanged(false);
    }
  }

  static void _showToast(String message) {
    Fluttertoast.showToast(
      msg: message,
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.CENTER,
      timeInSecForIosWeb: 1,
      backgroundColor: Colors.black87,
      textColor: Colors.white,
      fontSize: 16.0,
    );
  }
} 